### ISSUE TITLE
Why is sudo NOPASSWD option set for wheel group?

### ISSUE THREAD

**Issue by SimonTek** [cisagov/ansible-role-dev-ssh-access#21]
Why, of all Gov't agencies, CISA should be last agency to push passwordless sudo-ing.

**Comment by felddy** [comment]
@SimonTek thank you for reviewing the code.  You are correct that password-less sudo access should generally be avoided.   On the systems that use this ansible role, the users authenticate using ssh key pairs via [AWS SSM agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html).   That is, they do not have a password to use with sudo.   

- [x] I think it would make sense for us to add a comment to this code so other people don't read this as an endorsement for password-less sudo.

https://github.com/cisagov/ansible-role-dev-ssh-access/blob/ebdf53fea24049f9920e5df0c5bcc5845e91f053/tasks/main.yml#L9-L15

@jsf9k can add a bit more context about how this role will be evolving as we take more advantage of the AWS SSM agent. 

Thank you again for your contribution.

**Comment by jsf9k** [comment]
@SimonTek, we will be modifying our setup to allow privileged users to push their public `ssh` keys to instances, after which they will have a one minute window to log in.  See cisagov/cool-system#171.

At that point we will no longer need to create user accounts in the AMI, and we can rely on Kerberos authentication for `sudo`.
